### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by wstart** [devfeel/dotweb#103]
增加一个 contenct 字段 来获取上传的文件内容

**Comment by wstart** [comment]
buf := new(bytes.Buffer)
		buf.ReadFrom(upload.File)
		return buf.String()

**Comment by devfeel** [comment]
hello, now you can use UploadFile.Bytes() to get file content, it's supported on version 1.4.5+

**Comment by devfeel** [comment]
sorry, now you will use UploadFile.ReadBytes() to get file content, it's supported on version 1.4.6+
special:
if you read bytes, it's will cause empty data in UploadFile.File, so you use SaveFile will no any data to save
