### ISSUE TITLE
Suggest to add XML operation interface

### ISSUE THREAD

**Issue by 0123cf** [devfeel/dotweb#106]
=-=

**Comment by devfeel** [comment]
now you can use config.Config.IncludeConfigSet load xml\json\yaml config file
but, config file must like this:
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <set key="set1" value="1" />
    <set key="set2" value="2" />
    <set key="set3" value="3" />
    <set key="set4" value="4" />
</config>
