### ISSUE TITLE
能不能为静态目录专门增加一个设置路径的方法？

### ISSUE THREAD

**Issue by biij5698** [devfeel/dotweb#125]
1、app.HttpServer.ServerFile("/static/*filepath", "static")能不能把星号后面的filepath去掉？因为星号就代表全部了。
2、最好能增加一个设置静态目录的方法，参数里面直接填写静态目录的路径即可(要支持相对路径)，然后一个可选参数是数组形式，比如{"*.css","*.png"}，用于指定允许的静态文件类型。

**Comment by devfeel** [comment]
It is now supported in version 1.5.9.1

**Comment by devfeel** [comment]
目前在v1.7.4支持在注册静态资源路由时指定屏蔽哪些后缀名，可以满足你的需求
