### ISSUE TITLE
session存储方式为redis时能否指定key？

### ISSUE THREAD

**Issue by biij5698** [devfeel/dotweb#127]
redis://:123456@192.168.0.1:6379/0已经可以具体到db，能否具体到redis中的key？这样redis的db中只需要一层key就可以，不像默认的dotweb:session:be708d8c00....这么多层，有点复杂了。
而且自定义key还有个好处，在redis的同一个db中我可以存储多个网站的session，这个db就专门用来存放不同网站的session。

**Comment by devfeel** [comment]
Thanks！Now It's support on version 1.5.
you can use session.NewRedisConfig and set StoreKeyPre param.
