### ISSUE TITLE
router middleware handle http 404,405. cann`t response content-type:application/json 

### ISSUE THREAD

**Issue by lyw1995** [devfeel/dotweb#149]
code config server global handler :
![image](https://user-images.githubusercontent.com/13196763/44697349-f28a1580-aaad-11e8-956d-00356dbe5860.png)
![image](https://user-images.githubusercontent.com/13196763/44697382-19484c00-aaae-11e8-93c6-ea250151de7d.png)
test:
![image](https://user-images.githubusercontent.com/13196763/44697431-41d04600-aaae-11e8-918e-0b2fae04ee9a.png)
![image](https://user-images.githubusercontent.com/13196763/44697440-4bf24480-aaae-11e8-8c72-2c77ac0e23e7.png)

**Comment by devfeel** [comment]
thanks, now it's fixed on Version 1.5.7.4
