### ISSUE TITLE
关于获取客户端 IP 的一个小请求

### ISSUE THREAD

**Issue by hacfox** [devfeel/dotweb#164]
https://github.com/devfeel/dotweb/blob/021409381551b2c023ab70d673b01946135780dc/request.go#L148
你好，该方法无法获取更为准确且更多的客户端 IP 信息，是否可以考虑增加方法以实现更好的获取客户端信息。
比如 `echo`框架中的实现https://github.com/labstack/echo/blob/c54d9e8eed6ce2dfb8446ae6f9ac4eac800570bf/context.go#L258

**Comment by devfeel** [comment]
It is now supported in version 1.5.9.1
