### ISSUE TITLE
i cann't get  RemoteIP and RemoteAddr

### ISSUE THREAD

**Issue by yulibaozi** [devfeel/dotweb#20]
env:windows 10

code one:`fmt.Println(" ctx.RemoteIP():", ctx.RemoteIP())`
result two:` ctx.RemoteIP(): [`

code two:`fmt.Println("ctx.Request().RemoteAddr :",ctx.Request().RemoteAddr)`
result two:`ctx.Request().RemoteAddr : [::1]:59521`

I thought for a long time, but I can't think why

**《以下是文言文》**
在下， 日思夜寐，终不得果，望君解惑

**Comment by devfeel** [comment]
thanks! it's fixed now. at request.go line:111
