### ISSUE TITLE
老哥,能否考虑增加context支持

### ISSUE THREAD

**Issue by xingchendada** [devfeel/dotweb#22]
目前框架的超时需要自己在handle中处理,go1.7中加入的context包可以很好的处理超时后结束任务队列,
理想中的方式
func(ctx dotweb.Context){
ctx.glob["x"]//全局容器
ctx.settimeout=超时时间/time.after/超时chan
ctx.settimeoutfunc
.....do ....

}

**Comment by devfeel** [comment]
dotweb.Context增加Context() & SetTimeoutContext() & WithContext()
dotweb.Request增加自动生成unique RequestID,通过RequestID()获取,默认置入dotweb.Context.context中，以RequestID为key

**Comment by simplefunc** [comment]
nice.
