### ISSUE TITLE
复杂路由 跨域中间件 未生效问题

### ISSUE THREAD

**Issue by cometstone** [devfeel/dotweb#36]
func InitRouter(app *dotweb.DotWeb) {
	app.HttpServer.GET("/login/name/:name/password/:password", user.LoginHandler).Use(NewSimpleCROS())
}
func NewSimpleCROS() dotweb.Middleware {
	option := cors.NewConfig().UseDefault()
	return cors.Middleware(option)
}

结果中间件未生效
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

go版本
go version go1.8.3 darwin/amd64

**Comment by devfeel** [comment]
thanks, now is ok, please use last version.
