### ISSUE TITLE
can you create some type in ctx.Query...()

### ISSUE THREAD

**Issue by yulibaozi** [devfeel/dotweb#49]
hi,
   The author of the handsome，I am usering dotweb，it is  beautiful，but i have some tips:
i hope have ctx.QueryInt64()、ctx.QueryInt() and so on... but now  I find ctx,QueryString() only.

                                                                                                                         Happy working!

**Comment by cjg199055** [comment]
convert by yourself~

**Comment by devfeel** [comment]
now support on version 1.4.2 - https://github.com/devfeel/dotweb/tree/1.4.2
