### ISSUE TITLE
关于Module中间件的疑问

### ISSUE THREAD

**Issue by BingboLI** [devfeel/dotweb#5]
您好，我用Module来过滤未登录的用户，如果用户未登录则返回提示需要登录信息，End()表示提前中断请求，但是它会使我的OnEndRequest失效，它会在End()时就结束了Request，但是我在OnEndRequest里的一些操作就不会执行到，请问有什么方法可以让OnEndRequest也可以执行到呢？

**Comment by devfeel** [comment]
if set HttpContext.End,ignore user handler, but exec all http module

**Comment by devfeel** [comment]
you can view example\httpmodule

**Comment by BingboLI** [comment]
Thank you for your support！
