### ISSUE TITLE
dotweb & beego 不完全压力测试对比

### ISSUE THREAD

**Issue by forging2012** [devfeel/dotweb#67]
➜  src git:(master) ✗ wrk -c100 -t100 -d10s http://localhost:8081/dotweb
Running 10s test @ http://localhost:8081/dotweb
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.46ms    2.85ms  52.47ms   72.87%
    Req/Sec   314.86     68.44   820.00     73.04%
  315407 requests in 10.11s, 43.62MB read
Requests/sec:  31211.64
Transfer/sec:      4.32MB

➜  src git:(master) ✗ wrk -c100 -t100 -d10s http://localhost:8080/beego 
Running 10s test @ http://localhost:8080/beego
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.18ms    6.09ms  90.41ms   89.80%
    Req/Sec   261.17     90.74     3.06k    80.98%
  261108 requests in 10.10s, 38.85MB read
Requests/sec:  25862.00
Transfer/sec:      3.85MB

dotweb code:
package main

import (
	"fmt"

	"github.com/devfeel/dotweb"
)

func main() {
	//初始化DotServer
	app := dotweb.New()

	//开启debug模式
	app.SetDevelopmentMode()

	//设置路由
	InitRoute(app.HttpServer)

	//开始服务
	port := 8081
	err := app.StartServer(port)
	fmt.Println("dotweb.StartServer error => ", err)
}

func Hello(ctx dotweb.Context) error {
	ctx.WriteString("hello world!")
	return nil
}

func InitRoute(server *dotweb.HttpServer) {
	server.Router().GET("/", Hello)
	server.Router().GET("/hello", Hello)
	server.Router().GET("/dotweb", Hello)
}

beego code:

package main

import (
	"github.com/astaxie/beego"
)

type MainController struct {
	beego.Controller
}

func (c *MainController) Get() {
	c.Ctx.WriteString("Hello World!")
}

func main() {
	beego.Router("/", &MainController{})
	beego.Router("/beego", &MainController{})
	beego.Run()
}

**Comment by devfeel** [comment]
dotweb可以关闭调试模式，关闭默认日志，应该还会再提高一些。

**Comment by devfeel** [comment]
最近做了完整测试，针对dotweb、echo、gin
DotWeb | 1.9.2 | 16core16G |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cpu | 内存 | Samples | Average | Median | 90%Line | 95%Line | 99%Line | Min | Max | Error% | Throughput | Received KB/Sec | Send KB/Sec
40% | 39M | 15228356 | 19 | 4 | 43 | 72 | 204 | 0 | 2070 | 0.00% | 48703.47 | 7514.79 | 8656.28
40% | 42M | 15485189 | 18 | 4 | 41 | 63 | 230 | 0 | 3250 | 0.00% | 49512.99 | 7639.7 | 8800.16
40% | 44M | 15700385 | 18 | 3 | 41 | 64 | 233 | 0 | 2083 | 0.00% | 50203.32 | 7746.22 | 8922.86
  |   |   |   |   |   |   |   |   |   |   |   |   |  
ECHO | 1.9.2 | 16core16G |   |   |   |   |   |   |   |   |   |   |  
cpu | 内存 | Samples | Average | Median | 90%Line | 95%Line | 99%Line | Min | Max | Error% | Throughput | Received KB/Sec | Send KB/Sec
38% | 35M | 15307586 | 19 | 4 | 44 | 76 | 181 | 0 | 1808 | 0.00% | 48951.22 | 6166.71 | 9034.94
36% | 35M | 15239058 | 19 | 4 | 45 | 76 | 178 | 0 | 2003 | 0.00% | 48734.26 | 6139.37 | 8994.9
37% | 37M | 15800585 | 18 | 3 | 41 | 66 | 229 | 0 | 2355 | 0.00% | 50356.09 | 6343.68 | 9294.24
  |   |   |   |   |   |   |   |   |   |   |   |   |  
Gin  |  1.9.2 |  16core16G  |   |   |   |   |   |   |   |   |   |   |  
cpu | 内存 | Samples | Average | Median | 90%Line | 95%Line | 99%Line | Min | Max | Error% | Throughput | Received KB/Sec | Send KB/Sec
36% | 36M | 15109143 | 19 | 6 | 44 | 71 | 175 | 0 | 3250 | 0.00% | 48151.87 | 5877.91 | 8746.33
36% | 40M | 15255749 | 19 | 5 | 43 | 70 | 189 | 0 | 3079 | 0.00% | 48762.53 | 5952.45 | 8857.25
36% | 40M | 15385401 | 18 | 4 | 42 | 66 | 227 | 0 | 2312 | 0.00% | 49181.03 | 6003.54 | 8933.27

**Comment by forging2012** [comment]
Nice！
