### ISSUE TITLE
【建议】port:=8080  这能建议修改成这样的 app.port:=8080

### ISSUE THREAD

**Issue by forging2012** [devfeel/dotweb#68]
port:=8080  这能建议修改成这样的 app.port:=8080，保持风格统一。

**Comment by devfeel** [comment]
按目前dotweb的结构，port是对应到httpserver，app没有这样的职责，所以目前不会这样处理

**Comment by devfeel** [comment]
App的具体信息：http://www.cnblogs.com/pzrr/p/7668294.html
