### ISSUE TITLE
【BUG】app.HttpServer.SetEnabledGzip(true)设置gzip压缩后，访问页面返回空压缩包直接下载

### ISSUE THREAD

**Issue by forging2012** [devfeel/dotweb#72]
测试代码：

`
// FILENAME: dotweb-hello.go
// DATE: 23/10/2017
// AUTHOR: FORGING2012@GMAIL.COM
// Github: https://github.com/forging2012
// Description: dotweb-hello.go

package main

import (
	"fmt"

	"github.com/devfeel/dotweb"
)

func main() {
	app := dotweb.New()
	app.SetDevelopmentMode()

	//app.Start()

	app.HttpServer.SetEnabledGzip(true)

	//InitRoute(app.HttpServer)
	app.HttpServer.Router().GET("/", Hello)

	port := 8080
	//app.StartServer(port)
	err := app.StartServer(port)
	if err != nil {
		fmt.Println(err)
	}

}

func Hello(ctx dotweb.Context) error {
	ctx.WriteString("Hello world!")
	return nil
}
`

**Comment by devfeel** [comment]
测试了下，仅在WriteString存在。
原因为未显式设置MIME类型导致。、
WriteString默认设置为MIMETextPlainCharsetUTF8
已修复。

**Comment by forging2012** [comment]
OK
经过测试问题已经修复。
`Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:keep-alive`

@devfeel  速度给力啊~！
