### ISSUE TITLE
关于Bind的问题

### ISSUE THREAD

**Issue by BingboLI** [devfeel/dotweb#9]
Bind如果客户端传入了与字段不匹配的值则会引发panic，目前的Bind函数内没有对panic的拦截，可否加上panic拦截呢？

**Comment by cnphpbb** [comment]
暂时可以使用内部提供的错误处理模块方法[framework/exception](https://github.com/devfeel/dotweb/blob/master/framework/exception/exception.go) 来处理Bind函数的错误。 解决panic的拦截。

**Comment by devfeel** [comment]
like this:
err := ctx.Bind(user) or err := ctx.BindJsonBody(user)
you can check err and to do something
* print err
* log err
* other...
