### ISSUE TITLE
建议增加exuse方法用来实现exclude uri功能

### ISSUE THREAD

**Issue by EriconYu** [devfeel/dotweb#94]
比如我对"/"下的所有路径都使用middleware的use，但是"/login"我并不想过滤，可能还有一些别的uri也不想被过滤，希望增加exuse这个方法在实现“包括但除了”这个功能。

**Comment by devfeel** [comment]
fixed on https://github.com/devfeel/dotweb/pull/97
you can use like app.ExcludeUse(NewAccessFmtLog("appex"), "/")
